services:
  mysql:
    image: mysql:8.0
    container_name: epytodo-mysql
    env_file:
      - ./bonus/docker/services/db/mysql.env
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - epytodo-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-psuperstrongpassword',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  migration:
    build:
      context: .
      dockerfile: ./bonus/docker/services/changes/migrate.Dockerfile
    container_name: epytodo-migration
    env_file:
      - ./bonus/docker/services/changes/migrate.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - epytodo-network

  backend:
    build:
      context: .
      dockerfile: ./bonus/docker/services/backend/backend.Dockerfile
    container_name: epytodo-backend
    env_file:
      - ./bonus/docker/services/backend/backend.env
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      mysql:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - epytodo-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./bonus/frontend
      dockerfile: ../docker/services/frontend/frontend.Dockerfile
    container_name: epytodo-frontend
    env_file:
      - ./bonus/docker/services/frontend/frontend.env
    ports:
      - '80:3000'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - epytodo-network
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://frontend:3000',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  epytodo-network:
    driver: bridge

volumes:
  mysql_data:
