services:
  - type: web
    name: epytodo-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci && npx @rspack/cli build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
