name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        id: cache
        run: npm ci

  prettier:
    timeout-minutes: 10
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Add Prettier problem matcher
        run: echo "::add-matcher::.github/prettier-matcher.json"

      - name: Run Prettier check
        run: |
          npm run format -- --check --loglevel warn
          if [ $? -ne 0 ]; then
            echo "::error::Prettier found files that need formatting. Run 'npm run format' to fix them."
            exit 1
          fi

  eslint:
    timeout-minutes: 10
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Add ESLint problem matcher
        run: echo "::add-matcher::.github/eslint-matcher.json"

      - name: Run ESLint
        run: |
          npm run lint -- --format stylish
          if [ $? -ne 0 ]; then
            echo "::error::ESLint found issues that need to be fixed."
            exit 1
          fi

  test:
    timeout-minutes: 10
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm test -- --verbose
        env:
          CI: true

  e2e-test:
    timeout-minutes: 15
    needs: setup
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: epytodo
          MYSQL_USER: epytodo
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run database migration
        run: npm run migrate
        env:
          MYSQL_DATABASE: epytodo
          MYSQL_HOST: localhost
          MYSQL_USER: epytodo
          MYSQL_ROOT_PASSWORD: password
          PORT: 3000
          SECRET: test_secret

      - name: Start server in background
        run: npm run start &
        env:
          MYSQL_DATABASE: epytodo
          MYSQL_HOST: localhost
          MYSQL_USER: epytodo
          MYSQL_ROOT_PASSWORD: password
          PORT: 3000
          SECRET: test_secret

      - name: Wait for server to start
        run: |
          timeout 30s bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 1; done'

      - name: Run e2e tests
        run: npm run test:e2e -- --verbose
        env:
          MYSQL_DATABASE: epytodo
          MYSQL_HOST: localhost
          MYSQL_USER: epytodo
          MYSQL_ROOT_PASSWORD: password
          PORT: 3000
          SECRET: test_secret

  mirror:
    needs: [test, prettier, eslint, e2e-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      MIRROR_REPO: ${{ secrets.MIRROR_REPO }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Check if not mirror
        run: |
          if [ "$GITHUB_REPOSITORY" = "$MIRROR_REPO" ]; then
            echo "Already on mirror repository, skipping push"
            exit 0
          fi

      - name: Push to mirror
        run: |
          git remote add mirror git@github.com:${{ secrets.MIRROR_REPO }}.git
          git push mirror main
